version: 0.2
phases:
  install:
    runtime-versions:
      node: 16.14.0
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Testing started on `date`
      - npm run test
  build:
    commands:
      - echo Build started on `date`
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: build
